snakemkua\Warp12Bundle\Entity\Page:
    type: entity
    table: null
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
          type: nested
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        lvl:
            type: integer
            gedmo:
                - treeLevel
        name:
            type: string
            length: '128'
            unique: true
        title:
            type: string
            length: 255
            nullable: true
        metadescription:
            type: string
            length: 255
            nullable: true
        metakeywords:
            type: string
            length: 255
            nullable: true
        module:
            type: string
            length: 128
            nullable: true
        sortPriority:
            type: integer
            options:
                default: 0
        body:
            type: text
            nullable: true
        dateCreated:
            type: datetime
        dateUpdated:
            type: datetime
            nullable: true
        published:
            type: boolean
            options:
                default: true
        homepage:
            type: boolean
            options:
                default: false
    manyToOne:
        root:
            targetEntity: snakemkua\Warp12Bundle\Entity\Page
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeRoot
        parent:
            targetEntity: snakemkua\Warp12Bundle\Entity\Page
            inversedBy: children
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: snakemkua\Warp12Bundle\Entity\Page
            mappedBy: parent
            orderBy:
                lft: ASC
        urls:
            targetEntity: snakemkua\Warp12Bundle\Entity\Slug
            mappedBy: consumer
            orderBy:
                current: DESC

    lifecycleCallbacks: {}
