doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        quote_strategy: doctrine.orm.quote_strategy.ansi
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: yml
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree
                is_bundle: false
# Tree
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
  