<?php

namespace snakemkua\Warp12Bundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class Warp12Bundle extends Bundle
{
   public function registerCommands(Application $application)
    {
        return parent::registerCommands($application); // TODO: Change the autogenerated stub
    }
}
