<?php

namespace snakemkua\Warp12Bundle\Repository;

/**
 * SlugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlugRepository extends \Doctrine\ORM\EntityRepository
{
}
